services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=Simple_API_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Simple_API_DB
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  simpleapi:
    build: .   
    volumes:
      - .:/app  
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=Simple_API_user;Password=password;Database=Simple_API_DB
    ports:
      - 5000:80